### ISSUE TITLE
Support role provider profiles

### ISSUE THREAD

**Issue by krivachy** [loladotdev/lola#1]
### Describe the solution you'd like?

```shell
We use role profile to assume a role using an AWS SSO profile. This is because AWS SSO doesn't allow us to give developers fine grained permissions.

Example profile looks like this:


[profile assume-role]
role_arn = <arn>
role_session_name = <name>
source_profile = <aws sso profile>
```

Lola gives me the following error message:

> Role provider profiles are currently not supported by Lola.

This error is even returned when I have valid credentials in my `~/.aws/credentials` file for the profile.

If you don't want to support the auth flow then it would be nice to be able to at least use Lola if we fetch the credentials externally.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

_No response_

**Comment by aeby** [comment]
Thanks @krivachy for your report. We have already started working on this provider and we plan to ship this soon. As a workaround you could use [AWS Vault](https://github.com/99designs/aws-vault) for now if possible. We will track the progress of the role provider in this issue.

**Comment by moltar** [comment]
> As a workaround you could use [AWS Vault](https://github.com/99designs/aws-vault) for now if possible.

How do you do that? I already use `aws-vault`. Do I just launch the app from within the `exec`?

**Comment by moltar** [comment]
Hm,

```sh
$> aws-vault exec $PROFILE -- open -a lola
```

Is not working.

**Comment by moltar** [comment]
I think if Lola used the AWS creds from the environment, this would unlock many use cases right away. And doesn't sound like it'd be a difficult thing to do.

**Comment by aeby** [comment]
@moltar Thanks for the input. Regarding AWS Vault you can configure a profile to use an external [credential_process](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process):
```ini
[profile home]
credential_process = /opt/homebrew/bin/aws-vault exec home --json
```

Using the environment variables for the AWS credentials (like `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and friends) is a good idea and something we will look into.

**Comment by moltar** [comment]
> you can configure a profile to use an external [credential_process](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process):

Ah, good point!

Wouldn't want to lose `aws-vault` functionality tho, as I use it quite a bit in my scripts.

> good idea and something we will look into.

:+1:

**Comment by livioso** [comment]
We added support for assume role provider profiles in the [latest release v0.6.5](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v065-may-11-2022).
Would be lovely if you can shortly test if this works like it should and let us know if you have any problems. :)

**Comment by moltar** [comment]
Can't seem to get it to work...

Ran it both ways:

```sh
❯ aws-vault exec my-profile -- open -a Lola
```

```sh
❯ aws-vault exec my-profile -- /Applications/Lola/Lola.app/Contents/MacOS/Lola
```

And I am getting:

```
qml: Source profile not provided.
```

**Comment by aeby** [comment]
@moltar In this issues we track the missing support of `role_arn` and `source_profile`. Hence this doesn't solve your request for Lola to read the credentials from environment variables. I created a new issue (#12) for this request - feel free to follow this issue.

**Comment by iRoachie** [comment]
Hey @livioso, I wasn't able to get this working even with 0.6.5.

**Comment by livioso** [comment]
@iRoachie Thanks for letting us know! 💜 That's strange... Would be awesome if you can share the affected profile's setup with us (`~/.aws/config`) so that we can debug and fix this. :)

**Comment by iRoachie** [comment]
@livioso I see you refer to `config`, but this stuff is actually in `credentials`.

While I can't share the actual values, the `credentials` file setup is pretty simple.

```
[master]
aws_access_key_id=xx
aws_secret_access_key=xxx

[marketing]
role_arn=xx
source_profile=master
```

**Comment by livioso** [comment]
@iRoachie Ah! Thanks that explains it. :) We only take the config from the `config` file not the `credentials` file. We'll have a look into this.

**Comment by iRoachie** [comment]
Okay @livioso I suggest you not change what you have. From the [docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-role-overview) I see that the info about `role_arn` and `source_profile` should be in `config` even though It can be in `credentials`.

When I change it over to `config` it works as expected.
