### ISSUE TITLE
Log search `History` window does not close when switching tabs

### ISSUE THREAD

**Issue by joswayski** [loladotdev/lola#10]
### Describe the bug

```shell
If you switch tabs while a `History` of past search terms is open, the window will stay there across tabs.
```

### To Reproduce

Steps to reproduce:
1. Go to any logs resource
2. Search for something and press enter
3. Attempt to search for something else and wait for the history to come up
4. Switch tabs to another resource

### Expected behaviour

```shell
Window of `History` should close upon switching tabs
```

### Screenshots

Video: https://youtu.be/glgX4RuhDYU

### Operating System

macOS

### OS Version

12.3.1

**Comment by livioso** [comment]
Thanks for reporting. 😸 This should be fixed in the the latest [release v0.6.5](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v065-may-11-2022).
