### ISSUE TITLE
not following credential_process in ~/.aws/config

### ISSUE THREAD

**Issue by jakep36** [loladotdev/lola#13]
### Describe the bug

I use an external tool "leapp" to authenticate to aws, in my ~/.aws/config I define a `credential_process` for a given profile that uses the leapp cli to assume that role and get temp credentials.

### To Reproduce

Steps to reproduce:
1. Remove credentials for ~/.aws/credentials
2. Use a profile in ~/.aws/config with `credential_process` 
3. Attempt to use that profile with lola
4. View error in Messages

### Operating System

macOS

### OS Version

12.4

**Comment by aeby** [comment]
@jakep36 Thanks for the report. I quickly successfully tested a config profile with Leapp:
```ini
[profile leapp]
credential_process=/path/to/bin/leapp session generate SESSION_ID
region=eu-central-1
```
I got the session id by running `leapp session get-id`.

Can you please post the error message you see in Lola? Meanwhile you could try the following:
1. Maybe `leapp` is not in your `$PATH` and Lola is therefore unable to run the `credential_process`. Try to use the absolute path to  `leapp` in the config.
2. `leapp session generate` could fail to generate a valid JSON. Maybe you can quickly run the command to see if an appropriate JSON gets generated (see [Expected output from the Credentials program](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html)). 

Please let me know if it worked or what Lola reports as an error.

**Comment by jakep36** [comment]
Putting the absolute path to leapp in the ~/.aws/config for the profiles works. 

leapp is in my $PATH (`/opt/homebrew/bin`) and terminal apps were working without the absolute path, but this solves my issue. Let me know if there is any other debugging I can do to determine what Lola sees as my $PATH.

**Comment by aeby** [comment]
Thanks for the insights and debugging! There is definitely a bug in the current `$PATH` handling. I will let you know once we ship a fix and if you could then test this quickly that would very helpful and highly appreciated: :pray:

**Comment by livioso** [comment]
Thanks! 🎉 

We now take the `PATH` for the logging shell into account after [today's release](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v068-june-10-2022); there might still be corner cases where this problem can occur so we improved our error message to point out that specifying the absolute path is a solution in those cases.
