### ISSUE TITLE
Parsing rich text content on table views make them hard to use

### ISSUE THREAD

**Issue by duranmla** [loladotdev/lola#15]
### Describe the bug

```shell
I have a table with fields that has HTML and Markdown strings, those fields are being parsed and trying to display the rich text within, which makes hard to use the view.
```

### To Reproduce

Create a DynamoDB table with attributes that contain HTML string and you will see the problem.

### Expected behaviour

```shell
Values are not parsed from rich text to actual HTML
```

### Screenshots

<img width="2525" alt="CleanShot 2022-06-02 at 15 44 53@2x" src="https://user-images.githubusercontent.com/1425162/171643759-519526f0-b494-416f-b0ea-1128076efbd8.png">

### Operating System

macOS

### OS Version

12.2.1

**Comment by livioso** [comment]
Nice catch. Thanks for reporting 🙇‍♂️ 
Should be fixed in [today's release](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v067-june-3-2022).
