### ISSUE TITLE
JSON Formatting for cloudwatch events

### ISSUE THREAD

**Issue by arthurliebhardt** [loladotdev/lola#18]
### Describe the solution you'd like?

The sent logs in cloudwatch are not formatted and difficult to read for me as shown in the following image: 
![This is an image](https://i.postimg.cc/Wb1vZkmB/Screenshot-2022-06-25-at-18-27-02.png)

**Comment by aeby** [comment]
@arthurliebhardt Thanks again for the feedback.
This should be fixed in the release [0.6.9](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v069-july-22-2022)

**Comment by arthurliebhardt** [comment]
@aeby works great, love it. Thank you very much 🙏
