### ISSUE TITLE
Ability to launch an AWS console from the command palate or home page

### ISSUE THREAD

**Issue by bonovoxly** [loladotdev/lola#19]
### Describe the solution you'd like?

```shell
Having the ability to type something like `/awsconsole ACCOUNT1` and have the AWS web console load would be incredibly helpful. Or an `AWS CONSOLE` button on any page, that would then allow you to select your profile. No idea what the command switch should be, consider `/awsconsole` an example.

This is probably a feature that you would want to obsolete in the long run; a feature that if your tool was fully functional, would eliminate the need for the AWS console. But it's still would be useful.
```

### Is your feature request related to a problem? Please describe.

```shell
Would be very useful to rapidly get to the AWS console at a keystroke or 3.
```

**Comment by aeby** [comment]
Thanks for the input. I could also image a keyboard shortcut that just opens the console for the current account. Would that make sense?

**Comment by bonovoxly** [comment]
oh absolutely. almost would be preferred.

**Comment by ashishpandey001** [comment]
Sorry for the duplicate here - https://github.com/loladotdev/lola/issues/22

**Comment by aeby** [comment]
@bonovoxly Thanks again for the input.
We added the `Cmd + O` shortcut in the release [0.6.9](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v069-july-22-2022)
