### ISSUE TITLE
Add a follow or tail function for AWS cloudwatch logs

### ISSUE THREAD

**Issue by bonovoxly** [loladotdev/lola#20]
### Describe the solution you'd like?

```shell
Add the ability to follow or tail Cloudwatch logs.
```

### Is your feature request related to a problem? Please describe.

```shell
No problem. Just would be great to follow an active log.
```

**Comment by aeby** [comment]
This should work if you select a relative time range (i.e. last 5min). It fetches the latest log event automatically. Can you try that and let me know if this works for you?

**Comment by bonovoxly** [comment]
Ah, my mistake. Must have changed it to a selected time.

Appreciate it, closing.
