### ISSUE TITLE
ability to select AWS profiles using keyboard shortcuts

### ISSUE THREAD

**Issue by bonovoxly** [loladotdev/lola#21]
### Describe the bug

(This might be a new feature, and feel free to close this issue in favor of something more generic, like https://github.com/loladotdev/lola/issues/6 ).

It would be great if keyboard navigation worked to select an AWS profile. Right now, I can easily get to the search and begin searching for a profile/account, but once I filter, I can't actually SELECT using the keyboard. Am I missing something?

### To Reproduce

Steps to reproduce:
1. Go to `Select Account [A]`
2. Begin searching.
3. Attempt to select searched account without mouse clicking.

### Expected behaviour

```shell
Would be great if we could just `tab` to the account, then press `Enter` to select.
```

### Operating System

macOS

### OS Version

12.4

**Comment by aeby** [comment]
Thanks, this is a known problem for several UI components. We will address this once we streamline the interface and improve the overall keyboard navigation.
