### ISSUE TITLE
Weird CloudWatch entry order

### ISSUE THREAD

**Issue by linuxbasic** [loladotdev/lola#23]
### Describe the bug

```shell
log entries are not ordered correctly
```

### To Reproduce

Steps to reproduce:
1. Go to a CloudWatch Log Group
2. Change time filter or load new page

### Expected behaviour

```shell
Log entries are ordered by timestamp
```

### Screenshots

![Screenshot 2022-07-14 at 15 36 28](https://user-images.githubusercontent.com/688922/179100033-a63d1013-8f88-470e-ac37-6e167437c3ea.png)

### OS Version

MacOS 12.4 (21F79)

**Comment by aeby** [comment]
@linuxbasic  Thanks for the hint. Should be fixed in the release [0.6.9](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v069-july-22-2022)
