### ISSUE TITLE
Confusing Timezone Magic

### ISSUE THREAD

**Issue by linuxbasic** [loladotdev/lola#24]
### Describe the bug

```shell
When filtering CloudWatch logs, the timestamp get always converted to the local timezone which is very confusing. Also the format is inconsistent with how CloudWatch displays timestamps (ISO format).
```

### To Reproduce

Steps to reproduce:
1. Go to CloudWatch Log Group
2. Click on Time Filter
3. Select Manual Time Range

### Expected behaviour

```shell
In my perfect world, all timestamps are UTC and in the ISO format.

If you don't agree, it should at least accept the timezone I type in manually and display all timestamps accordingly. I don't really want to do timezone math after I got paged and the alarm report only contains UTC timestamps.

Cheers
Linus
```

### Screenshots

![Screenshot 2022-07-14 at 16 25 12](https://user-images.githubusercontent.com/688922/179118148-6f023afe-a1bb-44cb-b8ed-d2f479f12a3f.png)

### Operating System

macOS

### OS Version

12.4 (21F79)

**Comment by aeby** [comment]
@linuxbasic Thanks for the input. We now render the timestamps in the ISO format and added an option to switch between UTC and local timezone. See release [0.6.9](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v069-july-22-2022)
