### ISSUE TITLE
Lola creates invalid SSO token cache entry

### ISSUE THREAD

**Issue by kbakk** [loladotdev/lola#25]
### Describe the bug

We are using SSO login on AWS. 

When using Lola together with another tool (`aws-sso-login` or `aws` CLI), it causes some issues, and the SSO token cache has to be cleared.

Workaround:

Remove the cached SSO tokens: `rm ~/.aws/sso/cache/*.json` or `aws-sso-util logout`

### To Reproduce

Steps to reproduce:
1. Open Lola and log in using SSO provider
2. After logging in, attempt to use `aws --profile <sso profile> sts get-caller-identity`
3. See error: `Error loading SSO Token: Token for https://<host>/start is invalid` and exit code 255

### Expected behaviour

Lola will not create a token in SSO cache that's invalid (can't be used by botocore). `aws --profile <sso profile> sts get-caller-identity` to have exit code 0.

### Operating System

None

### Additional context

The issue was first reported in https://github.com/benkehoe/aws-sso-util/issues/88 where we discovered that Lola creates an invalid SSO token cache entry that is missing `expiresAt` key.

https://github.com/boto/botocore/blob/82aee347f401804eb9576fee36de19d2348a466b/botocore/utils.py#L3103

**Comment by aeby** [comment]
Thank you so much for the investigation and the detailed report! We will have a look at this and let you know once we have a fix ready.

**Comment by livioso** [comment]
@kbakk Thanks again for reporting this! It's fixed in 0.7.6 (rolled out for macOS, Linux will shortly follow).
