### ISSUE TITLE
"AWS Console" button (in EC2) opens non-default browser

### ISSUE THREAD

**Issue by skyzyx** [loladotdev/lola#3]
### Describe the bug

Pulling up an EC2 instance, my only option is "AWS Console". Clicking on it opens Google Chrome instead of my default web browser.

### To Reproduce

1. Search for "ec2".

2. Select any EC2 instance. 

3. Click "AWS Console". 

### Expected behaviour

The AWS Console should open in my default web browser.

### Operating System

macOS (the official™ name uses a lowercase "m")

### OS Version

12.3

**Comment by aeby** [comment]
Thanks a lot for your report. Let me first explain why this happens: To ensure you are logged into the correct AWS account we create a fresh browser profile for each account. The goal is to not mess with any AWS console session you may have already open in your browser.
For now we support Chrome and Firefox based browsers and check if we can find any of those on your system (Chrome being the first in the list).

To solve your request I see the following options:

1. You handle the AWS login yourself and Lola just opens the plain URL in your default browser (as you described)
2. You don't care if you get logged out of any AWS console session in your default browser and Lola opens the sign in URL in your default browser
3. You think separate browser profiles make sense but you would like to specify any of the supported browsers (Chrome, Chromium, Firefox, ...)

Thanks for your feedback.

**Comment by skyzyx** [comment]
IMO, managing AWS sessions in the same browser isn’t necessarily Lola’s problem to solve. AWS (still) doesn’t support multiple concurrent logins (like Google).

For me, I would expect my preferred browser to be used by default (Safari). If I need to open a different browser for a different session, I’ll just generate a new login URL from AWS Vault.

**Comment by aeby** [comment]
@skyzyx We added a [setting to override the default behavior](https://github.com/loladotdev/lola/wiki/Settings#use-default-browser-for-aws-console-links) and open your default browser in the [0.6.1 release](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v061-apr-6-2022). You can install this update by clicking on the update notification in Lola.
