### ISSUE TITLE
List of profiles is not space-efficient

### ISSUE THREAD

**Issue by skyzyx** [loladotdev/lola#4]
### Describe the bug

I have access to, and regularly manage, upwards of 180 AWS accounts. The list of profiles is incredibly space-inefficient.

### To Reproduce

1. Launch the app.

2. Select a profile. 

### Expected behaviour

No expectations per sé, but one-per-line on a 5K display is wasteful.

* Having an auto-focused field for filtering account names will help me select the one I want faster.

* Something multi-column maybe? Or a "dense" visual mode?

### Screenshots

<img width="2672" alt="lola-profiles" src="https://user-images.githubusercontent.com/39447/159802813-e960f5de-7003-4b9f-83dc-c08e63a57381.png">

### Operating System

MacOS

### OS Version

12.3

**Comment by aeby** [comment]
Very insightful, thanks. I think a search field could make a lot of sense in this case. 
What do you think about the idea of having the most recent used ones on top? Would that help or do you regularly access a lot of different ones?

**Comment by aeby** [comment]
@skyzyx We added a search field to the profile page in the [0.6.1 release](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v061-apr-6-2022). You can install this update by clicking on the update notification in Lola.

**Comment by skyzyx** [comment]
Thanks. I'll look again.

As a former AWS SDK and Console engineer, I can say that _most_ people only have a couple that they use a lot.

Nowadays, as someone who manages _hundreds_ of accounts in AWS Organizations, I regularly flip through several accounts per day, every day, and they're often different. But I expect that I am in the minority.

Perhaps something like "frequently-used" rather than _purely_ "recently-used" would have some value, where by the accounts that have the most frequent use in a rolling number of uses (as opposed to time) would bubble up to the top.

If I were to use Lola monthly, and I generally use several different accounts, but "abc" is always one of them, I would expect the algorithm to ensure that "abc" stays in the _frequent_ list.
