### ISSUE TITLE
How to see CloudWatch logs for lambda function?

### ISSUE THREAD

**Issue by duranmla** [loladotdev/lola#5]
When I try to go to the logs on Lola I don't see much. I only see when the last request has made, whereas on the AWS CloudWatch console I am able to see the actual logs for the function.

<img width="2543" alt="CleanShot 2022-04-07 at 10 25 39@2x" src="https://user-images.githubusercontent.com/1425162/162155064-8add8f34-1821-4451-901a-ef0e0adba2b7.png">

vs

<img width="2228" alt="CleanShot 2022-04-07 at 10 26 41@2x" src="https://user-images.githubusercontent.com/1425162/162155319-0a91b32d-2fad-4633-b7a6-0f51871bd7f7.png">

It's me that is missing something obvious or there is no current support for this?

> _Also, it is this the best channel to ask this "HOWTO" questions?_

Nice work folks! Great first impressions!

**Comment by livioso** [comment]
The Lambda to Cloudwatch logs flow is a bit work in progress:

What happened here is: We pre-fill the `REPORT` filter query in the search input box to get the latest invocation report:
If you remove the `REPORT` filter query you should see the same as log output. Also if you open the log group directly you should see the latest unfiltered logs.

> Also, it is this the best channel to ask this "HOWTO" questions?

For quick questions like this we also have a  [Discord](https://discord.com/invite/AagTc2nTxG) but issues are fine too, whatever works best for you :)

> Nice work folks! Great first impressions!

🙇 thanks for the kind words!
