### ISSUE TITLE
Support for console URL redirect config

### ISSUE THREAD

**Issue by wilhen01** [loladotdev/lola#9]
### Describe the solution you'd like?

Our AWS accounts are authenticated using certificates, which means that we have to log in using a "wormhole" redirect URL that handles the certificate auth. It's a standard template that looks like this: 

`https://wormhole.blah/account/<accountNumber>/console?destination=https://s3.console.aws.amazon.com/<whichever-resource-path>`

It would be cool to have the option to configure this URL redirect prefix within Lola so that the console links work on a single click rather than having to muck around with login.

**Comment by aeby** [comment]
Thanks for the feedback, interesting authentication strategy 😀. Are the `accountId` and `destinationURL` the only template parameters required or is there a need for more (like i.e. `region`)?

**Comment by wilhen01** [comment]
Account ID and destination URL are the only required parameters 🙂

**Comment by livioso** [comment]
We added a settings entry to [configure a custom URL template](https://github.com/loladotdev/lola/wiki/Settings#custom-url-template) in the [latest release v0.6.5](https://github.com/loladotdev/lola/blob/main/CHANGELOG.md#v065-may-11-2022). 🎊

**Comment by wilhen01** [comment]
@livioso 😍  thanks so much, exactly what we needed - works perfectly 😁

**Comment by livioso** [comment]
Great to hear! 👍😊
